### ISSUE TITLE
Acceleration on particle i

### ISSUE THREAD

**Issue by sahil5d** [Joost987/MONDPMesh#1]
A question about your paper, https://arxiv.org/abs/2312.02968 -- It mentions that for the simulation, "The particles can be Solar System planets, stars in a galaxy, or the galaxies in a galaxy cluster". Could you explain how the code would produce the total acceleration on a particle i where i is a planet?

Does the planet get its own pixel?

**Comment by Joost987** [comment]
Hi,

The particle gets represented by its coordinates, so its position and velocity vectors. It does not get its own pixel. The code produces the total acceleration on the particle by solving the AQUAL equation iteratively, and finding the potential field in this way. Then the acceleration at a certain point is simply the gradient of the potential. More details about this are in the paper, but if you have any specific questions, let me know!

**Comment by sahil5d** [comment]
Thanks! If it doesn't get its own pixel, then in the pixel it is in what else is contained?

Also, a planet has a total acceleration which is [a component to its host star] *plus* [a component to the galactic center]. Does the program sum those two components somewhere?

**Comment by Joost987** [comment]
The mass of the particle gets distributed to multiple pixels around its position using a Gaussian. Technically multiple particles could be in the same pixel, but there will probably be numerical errors if you do this. The program does not sum gravitational contributions from different planets/stars, like you would do in Newtonian gravity, as MOND, unlike Newtonian gravity, is not linear. It does calculate the total gravitational force though, so in a three body system every body would feel the gravity of the two other bodies. In MOND this is not the sum of the individual gravitational forces between the planets.

**Comment by sahil5d** [comment]
Thanks for your answers

> The mass of the particle gets distributed to multiple pixels around its position using a Gaussian. 

Ah so the planet is not treated like an individual entity which has a total acceleration. Unless I'm mistaken?

> The program does not sum gravitational contributions from different planets/stars, like you would do in Newtonian gravity, as MOND, unlike Newtonian gravity, is not linear.

I understand MOND is nonlinear, but still a planet (a real planet in the cosmos) has a total acceleration which has a component to the host star and a component to the galactic center and the total acceleration is the sum.

**Comment by Joost987** [comment]
The planet is an individual entity. It just gets smeared out over multiple pixels for numerical purposes. It still has 1 position in space, 1 velocity vector and 1 total acceleration vector.

**Comment by sahil5d** [comment]
Oh it occupies multiple pixels.

And then how is that 1 total acceleration vector calculated in your code or in AQUAL such that a simulated planet [has a total acceleration which has a component to the host star and a component to the galactic center and the total acceleration is the sum] ?

**Comment by Joost987** [comment]
The acceleration vector gets calculated for each of the pixels the planet is smeared out over, and from this the acceleration vector of the planet is found by applying the inverse of the operation that was used to smear out its mass. However, I have to repeat that its total acceleration is not the sum of the components, if we are applying the MOND phenomenology. The situation you describe is treated with something called the external field effect.

**Comment by sahil5d** [comment]
Does your code have an implementation of the EFE?

The bottom line is a planet could have an acceleration like 10^-3 m/s^2 to its host star and 10^-11 m/s^2 to its galactic center, each calculated differently, but total acceleration is their vector sum. Right? And I wonder if that kind of implementation can be found.

**Comment by Joost987** [comment]
This code does not have an implementation of the external field effect. The code has however been extended by my colleagues to include it, which should be released soon. In your example the planet is in the Newtonian regime, so its total acceleration is indeed the vector sum.

**Comment by sahil5d** [comment]
Instead of acceleration regimes and EFEs, how about a single function like this?:
```
const r_cutoff = 10^15 meters    // ~ 10,000 AU, this is a guess

function calc_accel_for_particle() {
    a_classic = 0
    a_far = 0

    for each mass:               // each mass in the 3D point cloud
        a_classic += Gm/r^2

    for each mass farther than r_cutoff:
        a_far += Gm/r^2
    a_far = sqrt(a_far * c^2/87Gly)

    a_total = a_classic + a_far

    return a_total
}
```

**Comment by Joost987** [comment]
I think there is some literature about using distance to distinguish regimes vs acceleration. You should check it out!
